# Generated by Django 4.2.7 on 2024-05-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessions",
            name="session_name",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
