# Generated by Django 4.2.7 on 2024-06-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_teacher_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="gender",
        ),
    ]
