# Generated by Django 4.2.7 on 2024-06-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_classroom_students_remove_classroom_teacher"),
        ("accounts", "0004_remove_customuser_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
