# Generated by Django 4.2.7 on 2024-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_teacher_user_delete_student_delete_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="total_recorded_score",
            field=models.FloatField(default=0),
        ),
    ]
