# Generated by Django 4.2.7 on 2024-08-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_sessions_total_recorded_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="total_quesitions",
            field=models.FloatField(default=0),
        ),
    ]
