# Generated by Django 4.2.7 on 2024-08-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_sessions_total_quesitions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessions",
            old_name="total_quesitions",
            new_name="total_questions",
        ),
    ]
