# Generated by Django 4.2.7 on 2024-09-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rename_total_quesitions_sessions_total_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
