# Generated by Django 4.2.7 on 2024-06-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="student",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
