# Generated by Django 4.2.7 on 2024-06-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_classroom_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="student",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="teacher",
        ),
    ]
