# Generated by Django 4.2.7 on 2024-06-04 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_gender"),
        ("main", "0003_remove_classroom_student_remove_classroom_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(blank=True, to="accounts.student"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.teacher",
            ),
        ),
    ]
