# Generated by Django 4.2.7 on 2024-06-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_classroom_students_classroom_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="students",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="teacher",
        ),
    ]
