# Generated by Django 4.2.7 on 2024-06-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_teacher_student_classroom_students_classroom_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
