# Generated by Django 4.2.7 on 2024-06-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_student_student_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="name",
            new_name="school_name",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="hashed_password",
            new_name="school_password",
        ),
    ]
