# Generated by Django 4.2.7 on 2024-06-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_name_school_school_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
