# Generated by Django 4.2.7 on 2024-07-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_classroom_teacher_classroom_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="random_name",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="option",
            name="random_picture",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="random_name",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="random_picture",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="random_sound",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
