# Generated by Django 4.2.7 on 2024-07-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_option_random_name_option_random_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="random_name",
        ),
        migrations.RemoveField(
            model_name="question",
            name="random_picture",
        ),
        migrations.RemoveField(
            model_name="question",
            name="random_sound",
        ),
        migrations.AddField(
            model_name="question",
            name="question_list",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
