# Generated by Django 4.2.7 on 2024-07-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_question_random_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="option_list",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
