# Generated by Django 4.2.7 on 2024-07-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_option_option_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="random_name",
        ),
        migrations.RemoveField(
            model_name="option",
            name="random_picture",
        ),
    ]
