# Generated by Django 4.2.7 on 2024-08-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_maxscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="maxscore",
            name="total_questions",
            field=models.FloatField(default=0),
        ),
    ]
