# Generated by Django 4.2.7 on 2024-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_question_write_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="first_letter",
            field=models.BooleanField(default=False),
        ),
    ]
