# Generated by Django 4.2.7 on 2024-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_question_first_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="last_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="second_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="third_letter",
            field=models.BooleanField(default=False),
        ),
    ]
