# Generated by Django 4.2.7 on 2024-10-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_question_last_letter_question_second_letter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="english_5",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="english_6",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="japanese",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="phonics",
            field=models.BooleanField(default=False),
        ),
    ]
