# Generated by Django 4.2.7 on 2024-10-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_test_english_5_test_english_6_test_japanese_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="numbers",
            field=models.BooleanField(default=False),
        ),
    ]
